config {
  type: "test",
  dataset: "view_dados_historicos_cvm_01"
}

input "dados_administrador" {
  select
    -21332113218712551 as id_admin,
    "05.491.567/0001-21" as cnpj_fundo,
    "2005-03-22" as data_registro_admin,
    "BANCO BNP PARIBAS BRASIL S/A" as administrador,
    "2005-03-21" as data_inicio_admin,
    "2016-11-24" as data_fim_admin
}
input "classe_fundo" {
  select
    -7860349436926082813 as id_classe,
    "05.491.567/0001-21" as cnpj_do_fundo,
    "2005-03-22" as data_registro_classe,
    "Fundo Cambial" as classe,
    "2005-03-21" as data_inicio_classe,
    "2008-11-28" as data_fim_classe
}

input "dados_gestor" {
  select
    -2484612740035277991 as id_gestor,
    "05.491.567/0001-21" as cnpj_fundo_gestor,
    "2005-03-22" as data_registro_gestor,
    "PJ" as pessoa_gestor,
    "02.562.663/0001-25" as cpf_cnpj_gestor,
    "BNP PARIBAS ASSET MANAGEMENT BRASIL LTDA" as gestor,
    "2003-03-14" as data_inicio_gestor,
    "2016-11-24" as data_fim_gestor
}
input "rentabilidade" {
  select
    -7894006515129742726 as id_rentabilidade,
    "05.491.567/0001-21" as cnpj,
    "2005-03-22" as data_registro,
    "Euro" as rentabilidade,
    "2005-03-21" as data_inicio_rent,
    "2008-11-28" as data_fim_rent
}
select 
  -21332113218712551 as id_admin,
  "05.491.567/0001-21" as cnpj_fundo,
  "2005-03-22" as data_registro_admin,
  "BANCO BNP PARIBAS BRASIL S/A" as administrador,
  "2005-03-21" as data_inicio_admin,
  "2016-11-24" as data_fim_admin,
  -7860349436926082813 as id_classe,
  "05.491.567/0001-21" as cnpj_do_fundo,
  "2005-03-22" as data_registro_classe,
  "Fundo Cambial" as classe,
  "2005-03-21" as data_inicio_classe,
  "2008-11-28" as data_fim_classe,
  -2484612740035277991 as id_gestor,
  "05.491.567/0001-21" as cnpj_fundo_gestor,
  "2005-03-22" as data_registro_gestor,
  "PJ" as pessoa_gestor,
  "02.562.663/0001-25" as cpf_cnpj_gestor,
  "BNP PARIBAS ASSET MANAGEMENT BRASIL LTDA" as gestor,
  "2003-03-14" as data_inicio_gestor,
  "2016-11-24" as data_fim_gestor,
  -7894006515129742726 as id_rentabilidade,
  "05.491.567/0001-21" as cnpj,
  "2005-03-22" as data_registro,
  "Euro" as rentabilidade,
  "2005-03-21" as data_inicio_rent,
  "2008-11-28" as data_fim_rent

