config {
  type: "table",
  schema: "staging"
}
select
  CNPJ_FUNDO as cnpj_fundo,
  CAST (DT_REG as string) as data_registro,
  PF_PJ_GESTOR as pessoa_gestor,
  CPF_CNPJ_GESTOR as cpf_cnpj_gestor,
  GESTOR as gestor,
  CAST (DT_INI_GESTOR as string) as data_inicio,
  CAST (DT_FIM_GESTOR as string) as data_fim
from
  ${ref("cvm_fi_hist_gestor")}
where 
  PF_PJ_GESTOR <> 'null'
  and CNPJ_FUNDO <> 'null'
